name: release-notifier

on:
  workflow_dispatch:
  schedule:
    # Scheduled everyday At 00:00
    - cron: '0 9 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: release-notifier-gh
        uses: maheshrayas/action-release-notifier@v2.1
        with:
          github_token: '${{ secrets.GH_TOKEN }}'
          type: Github
          repo: 'https://github.com/splunk/attack_range'
          days: 1
